### ISSUE TITLE
[Infra] autorizar contribuições a partir de forks

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/queries-basedosdados#900]
Atualmente o [action CD][action] responsável `Deploy`, `table-approve` e afins. Tem em seus [scripts][action-script] :

```yaml
name: CD
on:
  pull_request:
    types: [closed]
```
Que acaba por usar de base o repositório de origem do pull_request como referencia ao pegar as `secrets` para a  [action][action]
```yaml
name: CD
on:
  pull_request:
    types: [closed]
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GH_PAT: ${{ secrets.GH_PAT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_REGION: ${{ secrets.GKE_REGION }}
  BASEDOSDADOS_CONFIG: ${{ secrets.BASEDOSDADOS_CONFIG }}
  BASEDOSDADOS_CREDENTIALS_PROD: ${{ secrets.BASEDOSDADOS_CREDENTIALS_PROD }}
  BASEDOSDADOS_CREDENTIALS_STAGING: ${{ secrets.BASEDOSDADOS_CREDENTIALS_STAGING }}
  IMAGE_NAME: ghcr.io/basedosdados/queries-basedosdados
```
Um repositório que foi gerado a partir de um folk, parece não herda suas `secrets` o que já inviabiliza que PRs feitos de forks consigam realizar a [action][action] com sucesso.
  
Também essa [action][action] deveria ser sempre vinculada a `main` do repositório fonte como ambiente de sua execução.

Para facilitar contribuições futuras esse script tem que ser mudado. Alteração para algo como:

```yaml
on:
  push:
    branches: [main]
``` 
Onde esperamos acontecer um push na branch `main`  e executamos a [action][action] usando ela como ambiente.

[action]: https://github.com/basedosdados/queries-basedosdados/actions/workflows/cd.yaml
[action-script]: https://github.com/basedosdados/queries-basedosdados/blob/main/.github/workflows/cd.yaml
